ALTER TABLE players ALTER COLUMN pin DROP NOT NULL;
ALTER TABLE players ADD COLUMN IF NOT EXISTS pronoun TEXT;
ALTER TABLE players ADD COLUMN IF NOT EXISTS age INT CHECK (age IS NULL OR age BETWEEN 10 AND 99);
ALTER TABLE players ADD COLUMN IF NOT EXISTS email TEXT;
ALTER TABLE players ADD COLUMN IF NOT EXISTS phone TEXT;
ALTER TABLE players ADD COLUMN IF NOT EXISTS password_hash TEXT;

CREATE UNIQUE INDEX IF NOT EXISTS idx_players_email_unique ON players (LOWER(email)) WHERE email IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS idx_players_phone_unique ON players (phone) WHERE phone IS NOT NULL;